export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
export const EMPTY_CART="EMPTY_CART"

// FOR PRODUCT
export const PRODUCT_LIST="PRODUCT_LIST"
export const SET_PRODUCT_LIST="SET_PRODUCT_LIST"

// CART DATA FROM CART LIST
export const CART_LIST="CART_LIST"
export const SET_CART_LIST="SET_CART_LIST"

// INCREMENT QUANTITY FOR CART
export const INCREMENT_QUANTITY="INCREMENT_QUANTITY"
export const DECREMENT_QUANTITY="DECREMENT_QUANTITY"

